# This file configures the static analysis results for your Flutter project.

include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules are specified in the included file.
  rules:
    # You can customize rules here. For example:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enforce single quotes

# For more information about customizing analysis options, see
# https://dart.dev/guides/language/analysis-options
